
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 02 13:43:33 CEST 2009
//----------------------------------------------------

package hr.fer.anna.frisc.assembler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STOREH = 28;
  public static final int UVJ_Z = 59;
  public static final int OKTALNA_KONSTANTA = 75;
  public static final int STOREB = 27;
  public static final int UVJ_V = 53;
  public static final int PSEUDO_POSTO = 6;
  public static final int KRAJ_REDA = 72;
  public static final int UVJ_P = 58;
  public static final int HALT = 37;
  public static final int UVJ_N = 55;
  public static final int UVJ_M = 57;
  public static final int UVJ_C = 51;
  public static final int UVJ_UGT = 64;
  public static final int POCETNA_PRAZNINA = 71;
  public static final int UVJ_SGT = 68;
  public static final int MOVE = 22;
  public static final int UVJ_UGE = 66;
  public static final int POP = 30;
  public static final int SUB = 11;
  public static final int SHR = 18;
  public static final int UVJ_SGE = 70;
  public static final int LOADH = 25;
  public static final int SHL = 17;
  public static final int LOADB = 24;
  public static final int UVJ_ULT = 65;
  public static final int SBC = 12;
  public static final int UVJ_EQ = 61;
  public static final int KOMENTAR = 78;
  public static final int AP_DW = 43;
  public static final int L_ZAGRADA = 3;
  public static final int AP_DS = 42;
  public static final int UVJ_SLT = 69;
  public static final int STORE = 26;
  public static final int UVJ_ULE = 63;
  public static final int AP_END = 40;
  public static final int LABELA = 77;
  public static final int AP_ORG = 39;
  public static final int SR_REGISTAR = 8;
  public static final int UVJ_SLE = 67;
  public static final int PLUS = 5;
  public static final int ZAREZ = 2;
  public static final int DW = 44;
  public static final int JR = 32;
  public static final int ADD = 9;
  public static final int ADC = 10;
  public static final int JP = 31;
  public static final int PUSH = 29;
  public static final int DH = 46;
  public static final int ROTR = 21;
  public static final int LOAD = 23;
  public static final int DB = 45;
  public static final int ROTL = 20;
  public static final int EOF = 0;
  public static final int D_ZAGRADA = 4;
  public static final int PSEUDO_O = 50;
  public static final int OR = 15;
  public static final int PSEUDO_H = 49;
  public static final int error = 1;
  public static final int PSEUDO_D = 48;
  public static final int PSEUDO_B = 47;
  public static final int RET = 34;
  public static final int REGISTAR = 7;
  public static final int HEKSA_KONSTANTA = 74;
  public static final int BINARNA_KONSTANTA = 76;
  public static final int UVJ_NZ = 60;
  public static final int AP_EQU = 41;
  public static final int UVJ_NV = 54;
  public static final int AP_BASE = 38;
  public static final int UVJ_NN = 56;
  public static final int DEKADSKA_KONSTANTA = 73;
  public static final int RETN = 36;
  public static final int AND = 14;
  public static final int UVJ_NE = 62;
  public static final int RETI = 35;
  public static final int UVJ_NC = 52;
  public static final int ASHR = 19;
  public static final int CALL = 33;
  public static final int CMP = 13;
  public static final int XOR = 16;
}

